In [1]:
import numpy as np

In [2]:
arr=np.arange(50).reshape(2,5,5)

In [3]:
arr

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]],

       [[25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]]])

In [4]:
arr[0:,0:1,:]

array([[[ 0,  1,  2,  3,  4]],

       [[25, 26, 27, 28, 29]]])

In [9]:
arr[1,:,3:4]

array([[28],
       [33],
       [38],
       [43],
       [48]])

In [13]:
# BroadCasting 

x=np.array([[1,2,3]])
y=np.array([[1],[2],[3]])


In [14]:
x.shape, y.shape


((1, 3), (3, 1))

In [22]:
x+y


array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [23]:
x,y= np.broadcast_arrays(x,y)

In [18]:
x


array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [19]:
y

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [20]:
x+y


array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [24]:
# ------ PANDAS ------------------

In [25]:
import pandas as pd

In [31]:
s = pd.Series([11,22,33,44,55,66,77])
s

0    11
1    22
2    33
3    44
4    55
5    66
6    77
dtype: int64

In [33]:
s[3]


44

In [34]:
s[[4,6,0]]

4    55
6    77
0    11
dtype: int64

In [35]:
s[2]=200

In [36]:
s


0     11
1     22
2    200
3     44
4     55
5     66
6     77
dtype: int64

In [37]:
s[[5,0]]=[500,100]

In [38]:
s


0    100
1     22
2    200
3     44
4     55
5    500
6     77
dtype: int64

In [39]:
s[345]=4567


In [40]:
s


0       100
1        22
2       200
3        44
4        55
5       500
6        77
345    4567
dtype: int64

In [41]:
del s[4]


In [42]:
s


0       100
1        22
2       200
3        44
5       500
6        77
345    4567
dtype: int64

In [46]:
s1=pd.Series([111,222,333], index=['apples','mangoes','bananas'])

In [47]:
s1


apples     111
mangoes    222
bananas    333
dtype: int64

In [48]:
s2=pd.Series(s1, index=['grapes','apples','mangoes','bananas'])

In [49]:
s2


grapes       NaN
apples     111.0
mangoes    222.0
bananas    333.0
dtype: float64

In [50]:
s2.values


array([ nan, 111., 222., 333.])

In [51]:
s2.index


Index(['grapes', 'apples', 'mangoes', 'bananas'], dtype='object')

In [52]:
s2>200

grapes     False
apples     False
mangoes     True
bananas     True
dtype: bool

In [54]:
# Creating a SERIES using DICTIONARY!!>.................
dic={'name':'Muhammad Shariq','class':'AI','age':23}


In [55]:
dic


{'name': 'Muhammad Shariq', 'class': 'AI', 'age': 23}

In [56]:
s3=pd.Series(dic)

In [57]:
s3


name     Muhammad Shariq
class                 AI
age                   23
dtype: object

In [59]:
'apples' in s2


True

In [60]:
pd.isnull(s2)

grapes      True
apples     False
mangoes    False
bananas    False
dtype: bool

In [61]:
pd.notnull(s2)

grapes     False
apples      True
mangoes     True
bananas     True
dtype: bool

In [62]:
temp1= pd.Series([1,3,5,7], index=['one','three','five','seven'])

In [63]:
temp2= pd.Series([2,4,6,8], index=['two','four','six','eight'])

In [64]:
temp1 + temp2


eight   NaN
five    NaN
four    NaN
one     NaN
seven   NaN
six     NaN
three   NaN
two     NaN
dtype: float64

# DATAFRAMES

In [65]:
df= pd.DataFrame([1,3,5,6,7,8])

In [66]:
df


0
0  1
1  3
2  5
3  6
4  7
5  8

In [70]:
table= pd.DataFrame(['red','blue','green'], index=['x1','x2','x3'], columns=['colours'])

In [71]:
table

colours
x1     red
x2    blue
x3   green

# CREAting A DATA FRAME from Dictionary


In [72]:
score={'Quater 1':[45,67,88,87,56,89,90,23,58],
      'Quater 2':[45,66,77,88,99,70,87,45,67],
      'Quater 3':[55,67,76,78,79,87,90,98,96]}


In [73]:
piaic= pd.DataFrame(score)


In [74]:
piaic

Quater 1  Quater 2  Quater 3
0        45        45        55
1        67        66        67
2        88        77        76
3        87        88        78
4        56        99        79
5        89        70        87
6        90        87        90
7        23        45        98
8        58        67        96

In [76]:
piaic= pd.DataFrame(score, index=['Ali','Bilal','Ahmed','Daniyal','Faizan','Hamza','Shariq','Taimoor','Zafar'])

In [77]:
piaic

Quater 1  Quater 2  Quater 3
Ali            45        45        55
Bilal          67        66        67
Ahmed          88        77        76
Daniyal        87        88        78
Faizan         56        99        79
Hamza          89        70        87
Shariq         90        87        90
Taimoor        23        45        98
Zafar          58        67        96

In [78]:
piaic.loc[['Zafar','Shariq']]

Quater 1  Quater 2  Quater 3
Zafar         58        67        96
Shariq        90        87        90

In [79]:
piaic.loc[['Taimoor','Hamza']]['Quater 1']

Taimoor    23
Hamza      89
Name: Quater 1, dtype: int64

In [82]:
piaic.loc[['Taimoor','Hamza']] [['Quater 1','Quater 2','Quater 3']]

Quater 1  Quater 2  Quater 3
Taimoor        23        45        98
Hamza          89        70        87

In [84]:
piaic['Total']= piaic['Quater 1'] +piaic['Quater 2']+ piaic['Quater 3']


In [85]:
piaic


Quater 1  Quater 2  Quater 3  Total
Ali            45        45        55    145
Bilal          67        66        67    200
Ahmed          88        77        76    241
Daniyal        87        88        78    253
Faizan         56        99        79    234
Hamza          89        70        87    246
Shariq         90        87        90    267
Taimoor        23        45        98    166
Zafar          58        67        96    221

In [89]:
del piaic['Percentage']

In [90]:
piaic

Quater 1  Quater 2  Quater 3  Total
Ali            45        45        55    145
Bilal          67        66        67    200
Ahmed          88        77        76    241
Daniyal        87        88        78    253
Faizan         56        99        79    234
Hamza          89        70        87    246
Shariq         90        87        90    267
Taimoor        23        45        98    166
Zafar          58        67        96    221

In [91]:
piaic['Percentage']= (piaic['Total']*100)/300

In [92]:
piaic

Quater 1  Quater 2  Quater 3  Total  Percentage
Ali            45        45        55    145   48.333333
Bilal          67        66        67    200   66.666667
Ahmed          88        77        76    241   80.333333
Daniyal        87        88        78    253   84.333333
Faizan         56        99        79    234   78.000000
Hamza          89        70        87    246   82.000000
Shariq         90        87        90    267   89.000000
Taimoor        23        45        98    166   55.333333
Zafar          58        67        96    221   73.666667

In [97]:
piaic['Result']=np.where(piaic['Percentage'] > 70,'PASS','FAIL')

In [98]:
piaic


Quater 1  Quater 2  Quater 3  Total  Percentage Result
Ali            45        45        55    145   48.333333   FAIL
Bilal          67        66        67    200   66.666667   FAIL
Ahmed          88        77        76    241   80.333333   PASS
Daniyal        87        88        78    253   84.333333   PASS
Faizan         56        99        79    234   78.000000   PASS
Hamza          89        70        87    246   82.000000   PASS
Shariq         90        87        90    267   89.000000   PASS
Taimoor        23        45        98    166   55.333333   FAIL
Zafar          58        67        96    221   73.666667   PASS

In [106]:
piaic['Status']=['PASS' if perc>70 else "FAIL" for perc in piaic['Percentage']]


In [100]:
piaic


Quater 1  Quater 2  Quater 3  Total  Percentage Result Status
Ali            45        45        55    145   48.333333   FAIL   FAIL
Bilal          67        66        67    200   66.666667   FAIL   FAIL
Ahmed          88        77        76    241   80.333333   PASS   PASS
Daniyal        87        88        78    253   84.333333   PASS   PASS
Faizan         56        99        79    234   78.000000   PASS   PASS
Hamza          89        70        87    246   82.000000   PASS   PASS
Shariq         90        87        90    267   89.000000   PASS   PASS
Taimoor        23        45        98    166   55.333333   FAIL   FAIL
Zafar          58        67        96    221   73.666667   PASS   PASS

In [109]:
del piaic['Status']


In [110]:
piaic


Quater 1  Quater 2  Quater 3  Total  Percentage Result Revise-Status
Ali            45        45        55    145   48.333333   FAIL          FAIL
Bilal          67        66        67    200   66.666667   FAIL          PASS
Ahmed          88        77        76    241   80.333333   PASS          PASS
Daniyal        87        88        78    253   84.333333   PASS          PASS
Faizan         56        99        79    234   78.000000   PASS          FAIL
Hamza          89        70        87    246   82.000000   PASS          PASS
Shariq         90        87        90    267   89.000000   PASS          PASS
Taimoor        23        45        98    166   55.333333   FAIL          FAIL
Zafar          58        67        96    221   73.666667   PASS          FAIL

In [111]:
piaic['Revise-Status']=np.where((piaic['Quater 1'] > 60) &(piaic['Quater 2']>60) & (piaic['Quater 3']>60),"PASS","FAIL")

In [112]:
piaic

Quater 1  Quater 2  Quater 3  Total  Percentage Result Revise-Status
Ali            45        45        55    145   48.333333   FAIL          FAIL
Bilal          67        66        67    200   66.666667   FAIL          PASS
Ahmed          88        77        76    241   80.333333   PASS          PASS
Daniyal        87        88        78    253   84.333333   PASS          PASS
Faizan         56        99        79    234   78.000000   PASS          FAIL
Hamza          89        70        87    246   82.000000   PASS          PASS
Shariq         90        87        90    267   89.000000   PASS          PASS
Taimoor        23        45        98    166   55.333333   FAIL          FAIL
Zafar          58        67        96    221   73.666667   PASS          FAIL

In [119]:
#piaic['Grade']=["C" if (perc>60 and perc<70) "B" elif (perc>70 and perc<80) "A" elif(perc>80 and perc<90)  else "A+" for perc in piaic['Percentage']]

In [121]:
del piaic['Grade']


In [122]:
piaic


Quater 1  Quater 2  Quater 3  Total  Percentage Result Revise-Status
Ali            45        45        55    145   48.333333   FAIL          FAIL
Bilal          67        66        67    200   66.666667   FAIL          PASS
Ahmed          88        77        76    241   80.333333   PASS          PASS
Daniyal        87        88        78    253   84.333333   PASS          PASS
Faizan         56        99        79    234   78.000000   PASS          FAIL
Hamza          89        70        87    246   82.000000   PASS          PASS
Shariq         90        87        90    267   89.000000   PASS          PASS
Taimoor        23        45        98    166   55.333333   FAIL          FAIL
Zafar          58        67        96    221   73.666667   PASS          FAIL